run_fwupgrade: support emmc-less upgrade tarballs
Some developers create upgrade tarballs for nor flash components only, but
running upgrade with '-U' expects all images to be normally present.
As emmc images are normally not part of image.json and are added
unconditionally, make their addition to the list of upgrade components
conditional on presence of the bootloader image (which is something they
were already expecting anyway).

Solves:
/tmp/bin/flash_tools/install_tools/run_fwupgrade.py -U --image_url http://ferino-vm1.fungible.local/sbp_images/17842
Traceback (most recent call last):
  File "/tmp/bin/flash_tools/install_tools/run_fwupgrade.py", line 603, in main
    release_images = prepare(args)
  File "/tmp/bin/flash_tools/install_tools/run_fwupgrade.py", line 162, in prepare
    return prepare_offline(args, release_dir)
  File "/tmp/bin/flash_tools/install_tools/run_fwupgrade.py", line 127, in prepare_offline
    images['emmc'] = select('emmc_image.bin', release['signed_images']['boot.img.signed'])
KeyError: 'boot.img.signed'

Signed-off-by: Marcin Nowakowski <marcin.nowakowski@fungible.com>