enrollment_tools: fix customer certificate handling
When a customer certificate (and no fungible certificate) is sent to the
server to sign an image, the servers generates an exception in response:

Traceback (most recent call last):
  File "/usr/lib/cgi-bin/signing_server.cgi", line 236, in main_program
    sign_image()
  File "/usr/lib/cgi-bin/signing_server.cgi", line 216, in sign_image
    key_label, certificate, customer_certificate)
  File "/usr/lib/cgi-bin/signing_server.cgi", line 151, in image_gen
    customer_to_be_signed = add_cert_and_signature_to_binary(b'', cert, signature)
  File "/usr/lib/cgi-bin/signing_server.cgi", line 97, in add_cert_and_signature_to_binary
    binary += cert
TypeError: can't concat NoneType to bytes

Fix this by generating an empty bytes object instead of None when
reading non-existant form data.

Signed-off-by: Marcin Nowakowski <marcin.nowakowski@fungible.com>