TraceParser: fix S2 trace processing
Output format for S2 samurai traces has changed slightly and the
timestamp is now reported as a float ... this results in the following
crash:

Parsing trace.
Traceback (most recent call last):
  File "/home/robotpal/pipeline/TraceParser/tprs.py", line 578, in <module>
    filterlist, options.follow, core_id)
  File "/home/robotpal/pipeline/TraceParser/tprs.py", line 426, in read_trace
    args = tutils_sim.ParseLine(line)
  File "/home/robotpal/pipeline/TraceParser/tutils_sim.py", line 17, in ParseLine
    'time': int(args[6][5:])}
ValueError: invalid literal for int() with base 10: '163920498.7'

Fix this by doing an explicit string->float->int conversion. For older
palladium models it's unnecessary, but works correctly, so it's easier
to do that rather than have some extra conditional processing ...

Signed-off-by: Marcin Nowakowski <marcin.nowakowski@fungible.com>