SWTOOLS-2152: missmap hates wiq variables.
Some wiq_s1.c variables cause gdb to fall over during missmap with the following error:

    File "gdb_ident.py", line 281, in mksymlist
    address = sym.value().cast(gdb.lookup_type("uintptr_t"))
    gdb.error: You can't do that without a process to debug.

The culprits are wiq_record_disabled_hash_table and wiq_bit_disabled_hash_table, and the cast() is the cause of the error. Closer inspection shows they are the only variables of type gdb.SYMBOL_LOC_CONST_BYTES in an S1 binary. According to the sparse gdb documentation, gdb.SYMBOL_LOC_CONST_BYTES has no address and its value is a byte sequence - explaining the cast failure.

The proposed solution is to skip symbols of this type, much like we skip symbols of type gdb.SYMBOL_LOC_CONST. Without an address I don't think we can do much.